### ISSUE TITLE
[BUG] Notification in Steam

### ISSUE THREAD

**Issue by barbiehunter** [redsigma/UPMetroSkin#33] opened 2019-08-17 17:48 UTC
I'm using the latest version of Github before you ask me if I'm using the latest.
![image](https://user-images.githubusercontent.com/38357837/63215509-c2f17480-c127-11e9-94ee-028d98038c0b.png)

**Comment by redsigma** [comment] 2019-11-02 15:38
This it's a problem from valve not from the skin.

**Comment by Chaython** [comment] 2019-11-14 08:55
> I'm using the latest version of Github before you ask me if I'm using the latest.
> ![image](https://user-images.githubusercontent.com/38357837/63215509-c2f17480-c127-11e9-94ee-028d98038c0b.png)

This has been an issue for a long time, use the friends/chat window to manage groups/friends [the notification counter there works]
![image](https://user-images.githubusercontent.com/6486343/68841500-f63d9400-0681-11ea-9938-b7fe9a6c079e.png)

**Comment by go0d0ne** [comment] 2020-02-02 11:23
this is not a bug in skin... we should close this issue.

**Closed as completed** 2020-04-17 20:17 UTC
